const fs = require('fs');
let dash = fs.readFileSync('packages/web/src/pages/Dashboard.tsx', 'utf8');

dash = dash.replace(
  `            {/* Workflow & Quick Links */}`,
  `            {/* Operations Hub Quick Links */}\n            <div className="card-compact mb-6">\n              <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-zinc-400 mb-4">Operations Hub</h3>\n              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">\n                <button onClick={() => setActiveTab?.('finance')} className="p-3 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 hover:border-emerald-500/30 text-left transition-all group">\n                  <p className="text-xs font-bold text-slate-900 dark:text-white mb-1 group-hover:text-emerald-500">Finance</p>\n                  <p className="text-[9px] text-slate-500 dark:text-zinc-400">Fees & Payments</p>\n                </button>\n                <button onClick={() => setActiveTab?.('tuckshop')} className="p-3 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 hover:border-orange-500/30 text-left transition-all group">\n                  <p className="text-xs font-bold text-slate-900 dark:text-white mb-1 group-hover:text-orange-500">Tuckshop</p>\n                  <p className="text-[9px] text-slate-500 dark:text-zinc-400">Inventory & Sales</p>\n                </button>\n                <button onClick={() => setActiveTab?.('hostel')} className="p-3 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 hover:border-blue-500/30 text-left transition-all group">\n                  <p className="text-xs font-bold text-slate-900 dark:text-white mb-1 group-hover:text-blue-500">Hostel</p>\n                  <p className="text-[9px] text-slate-500 dark:text-zinc-400">Rooms & Boarding</p>\n                </button>\n                <button onClick={() => setActiveTab?.('clinic')} className="p-3 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 hover:border-red-500/30 text-left transition-all group">\n                  <p className="text-xs font-bold text-slate-900 dark:text-white mb-1 group-hover:text-red-500">Clinic</p>\n                  <p className="text-[9px] text-slate-500 dark:text-zinc-400">Health Records</p>\n                </button>\n              </div>\n            </div>\n\n            {/* Workflow & Quick Links */}`
);

fs.writeFileSync('packages/web/src/pages/Dashboard.tsx', dash);
console.log('patched');
