name = "ndovera-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
routes = [
	{ pattern = "ndovera.com/api/*", zone_name = "ndovera.com" },
	{ pattern = "www.ndovera.com/api/*", zone_name = "ndovera.com" },
	{ pattern = "ndovera.com/files/*", zone_name = "ndovera.com" },
	{ pattern = "www.ndovera.com/files/*", zone_name = "ndovera.com" }
]

[[d1_databases]]
binding = "APP_DB"
database_id = "77d6f37d-7fc8-4f5d-927c-42f3c6f24538"
database_name = "ndovera-db"

[vars]
CORS_ORIGIN = "https://ndovera.com,https://www.ndovera.com"
HYPERDRIVE_CONNECTION_STRING = ""
SESSION_COOKIE_NAME = "ndovera_session"
SESSION_TTL_SECONDS = "2592000"
FLUTTERWAVE_REDIRECT_BASE_URL = "https://ndovera.com"
TENANT_BASE_DOMAIN = "ndovera.com"

[[kv_namespaces]]
binding = "SESSIONS"
id = "3b679aac9c5a44f8bcc191f1f336d9af"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "dovera-files"