import React from 'react';
import { AlertCircle, BookOpen, Video } from 'lucide-react';
import { DashboardShell } from './DashboardShell';
import { StatGrid } from './StatGrid';
import type { DashboardCommonProps } from './types';

export function AdministrationDashboard({ currentUser, setActiveTab, stats, financeStats, students, teachers, teacherSummary, liveClassData }: DashboardCommonProps) {
  return (
    <DashboardShell title={`Welcome to the Command Center, ${currentUser?.name || 'Head of School'}`} subtitle="Here is your immediate overview of academic, financial, and operational health.">
      <StatGrid stats={stats} />
      <div className="grid grid-cols-1 xl:grid-cols-[1fr_2fr_1fr] gap-6 mt-6">
        <div className="space-y-6"><div className="card-compact"><h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400 mb-4">Command Actions</h3><div className="grid gap-3">{['approvals','announcements','staff','duty-report'].map((tab, i) => <button key={tab} onClick={() => setActiveTab?.(tab)} className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 text-left"><span className="text-xs font-bold text-white">Action {i + 1}</span></button>)}</div></div><div className="card-compact bg-emerald-50 dark:bg-emerald-600/5 border-emerald-200 dark:border-emerald-500/10"><h3 className="text-xs font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-500 mb-3">System Health</h3></div></div>
        <div className="space-y-6"><div className="card-compact"><h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400 mb-4">Live Performance Overview</h3><div className="space-y-4"><div><div className="flex justify-between text-[10px] font-bold uppercase tracking-widest mb-1.5"><span className="text-zinc-500">Classes Created</span><span className="text-white">{teacherSummary?.stats?.classCount || 88}%</span></div><div className="h-1.5 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-emerald-500" style={{ width: `${teacherSummary?.stats?.classCount || 88}%` }} /></div></div><div><div className="flex justify-between text-[10px] font-bold uppercase tracking-widest mb-1.5"><span className="text-zinc-500">Financial Target</span><span className="text-white">{financeStats ? Math.min(100, Math.round((financeStats.totalCollected / Math.max(1, financeStats.totalCollected + financeStats.outstanding)) * 100)) : 75}%</span></div><div className="h-1.5 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-blue-500" style={{ width: `${financeStats ? Math.min(100, Math.round((financeStats.totalCollected / Math.max(1, financeStats.totalCollected + financeStats.outstanding)) * 100)) : 75}%` }} /></div></div></div></div><div className="card-compact"><div className="flex items-center justify-between mb-4"><h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400">Critical Alerts & Approvals</h3><button className="text-[10px] font-bold text-emerald-500 hover:underline">See All</button></div><div className="space-y-3">{[`${students?.length || 0} students active`, `${teachers?.length || 0} staff active`, `${liveClassData?.length || 0} live classes`].map((text, i) => <div key={i} className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5"><AlertCircle size={14} className="text-blue-500" /><span className="text-xs font-bold text-slate-800 dark:text-zinc-200">{text}</span></div>)}</div></div></div>
        <div className="space-y-6"><div className="card-compact"><div className="flex items-center gap-2 mb-4"><Video size={16} className="text-violet-500" /><h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400">Classrooms Airspace</h3></div></div><div className="card-compact"><div className="flex items-center gap-2 mb-4"><BookOpen size={16} className="text-pink-500" /><h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400">Birthdays</h3></div></div></div>
      </div>
    </DashboardShell>
  );
}